[project]
name = "nanoflux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pathtype>=1.0.0",
    "rich>=14.2.0",
    "rich-argparse>=1.7.2",
    "liblinear-official==2.50.0",
    "joblib==1.5.2",
    "numpy==2.2.6",
    "pandas==2.3.2",
    "scikit-learn==1.7.1",
]

[project.scripts]
nanoflux = "src.main:run"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "data*"]

[tool.setuptools.package-data]
data = [
    "misc/*.csv",
    "misc/*.bed",
    "models/*.model",
    "models/*.onehot",
    "models/*.features",
    "refs/*.fa"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"