import argparse
import sys
from importlib.resources import files

import pathtype
from rich_argparse import RichHelpFormatter

from src.tasks import infer, prepare

VERSION = "0.0.1"


def run():
    parser = argparse.ArgumentParser(
        prog="nanoflux",
        epilog=f"Version {VERSION}",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument("-V", "--version", action="version", version=VERSION)

    # Parent parser for common arguments
    common_parser = argparse.ArgumentParser(add_help=False)
    common_parser.add_argument(
        "-o",
        "--output",
        type=pathtype.Path(writable_or_creatable=True),
        required=True,
        help="Directory to save output files to. To create one upon nonexistence, pass -c/--create-dir",
    )
    common_parser.add_argument(
        "-c",
        "--create-dir",
        action="store_true",
        help="Create output directory and parents",
    )
    common_parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=4,
        help="Number of threads to use in tool calls and inference",
    )
    common_parser.add_argument(
        "-d", "--debug", action="store_true", help="Enable debug logging"
    )

    subparsers = parser.add_subparsers(
        title="subcommands", dest="command", required=True, metavar="COMMAND"
    )

    prepare_parser = subparsers.add_parser(
        "prepare",
        help="Prepare a SAM/BAM file for nanoflux inference",
        formatter_class=parser.formatter_class,
        parents=[common_parser],
    )

    # required args:
    prepare_parser.add_argument(
        "-i",
        "--input",
        type=pathtype.Path(exists=True, name_matches_re=r"\.[sb]am$", readable=True),
        required=True,
        help="Path to input SAM/BAM file",
    )

    # optional args:
    prepare_parser.add_argument(
        "--ref",
        type=pathtype.Path(exists=True, name_matches_re=r"\.fa$", readable=True),
        required=False,
        default=files("data") / "refs" / "chm13v2.fa",
        help="Path to T2T CHM13v2.0 reference genome",
    )
    prepare_parser.add_argument(
        "--skip-alignment",
        action="store_true",
        help="Skip alignment if SAM/BAM is already aligned to T2T CHM13v2.0",
    )
    prepare_parser.add_argument(
        "--skip-sort-index",
        action="store_true",
        help="Skip sorting and indexing if SAM/BAM is already sorted and indexed",
    )
    prepare_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Perform a dry-run without actually processing or writing files",
    )

    prepare_parser.set_defaults(func=prepare)

    infer_parser = subparsers.add_parser(
        "infer",
        help="Infer from a file generated by nanoflux prepare",
        formatter_class=parser.formatter_class,
        parents=[common_parser],
    )
    infer_parser.add_argument(
        "-i",
        "--input",
        type=pathtype.Path(exists=True, name_matches_re=r"\.bed$", readable=True),
        required=True,
        help="Path to input bed file",
    )
    infer_parser.add_argument(
        "-m",
        "--model",
        choices=["brain_only", "pancancer_coarse_lbls", "pancancer_fine_lbls"],
        default="brain_only",
        help="Model to use for inference (default: brain_only)",
    )

    infer_parser.set_defaults(func=infer)

    args = parser.parse_args(
        args=None if sys.argv[1:] else ["--help"]
    )  # display help if no subcommand is passed
    args.func(args)


if __name__ == "__main__":
    run()
