import argparse
import sys
from importlib.resources import files

import pathtype
from rich_argparse import RichHelpFormatter

from src.tasks import infer, prepare, score
from src.utils.types import min_max_float

VERSION = "0.0.1"


def run():
    parser = argparse.ArgumentParser(
        prog="nanoflux",
        epilog=f"Version {VERSION}",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument("-V", "--version", action="version", version=VERSION)

    # Parent parser for common arguments
    common_parser = argparse.ArgumentParser(add_help=False)
    common_parser.add_argument(
        "-o",
        "--output",
        type=pathtype.Path(writable_or_creatable=True),
        required=True,
        help="Directory to save output files to. To create one upon nonexistence, pass -c/--create-dir",
    )
    common_parser.add_argument(
        "-c",
        "--create-dir",
        action="store_true",
        help="Create output directory and parents",
    )
    common_parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=4,
        help="Number of threads to use in tool calls and inference",
    )
    common_parser.add_argument(
        "-d", "--debug", action="store_true", help="Enable debug logging"
    )

    subparsers = parser.add_subparsers(
        title="subcommands", dest="command", required=True, metavar="COMMAND"
    )

    prepare_parser = subparsers.add_parser(
        "prepare",
        help="Prepare a SAM/BAM file for nanoflux inference",
        formatter_class=parser.formatter_class,
        parents=[common_parser],
    )

    # required args:
    prepare_parser.add_argument(
        "-i",
        "--input",
        type=pathtype.Path(exists=True, name_matches_re=r"\.[sb]am$", readable=True),
        required=True,
        help="Path to input SAM/BAM file",
    )

    # mutually exclusive args (default handled if none passed):
    reference = prepare_parser.add_mutually_exclusive_group(required=False)
    reference.add_argument(
        "--chm13v2",
        action="store_const",
        dest="ref",
        const="chm13v2",
        default="chm13v2",
        help="Use T2T CHM13v2.0 reference and annotation. Cannot be used with --hg38. Overrides --ref and --anno if those are also passed.",
    )
    reference.add_argument(
        "--hg38",
        action="store_const",
        dest="ref",
        const="hg38",
        help="Use hg38 reference and annotation. Cannot be used with --chm13v2. Overrides --ref and --anno if those are also passed.",
    )
    reference.add_argument(
        "--hg38-as",
        action="store_const",
        dest="ref",
        const="hg38-as",
        help="Use hg38 analysis set reference and annotation. Cannot be used with --chm13v2. Overrides --ref and --anno if those are also passed.",
    )

    # optional args:
    prepare_parser.add_argument(
        "--skip-alignment",
        action="store_true",
        help="Skip alignment if SAM/BAM is already aligned to T2T CHM13v2.0",
    )

    bam = prepare_parser.add_mutually_exclusive_group(required=False)
    bam.add_argument(
        "--skip-sort-index",
        action="store_true",
        help="Skip sorting and indexing if SAM/BAM is already sorted and indexed",
    )
    bam.add_argument(
        "--min-mapq",
        type=int,
        default=0,
        help="Minimum MAPQ to retain an alignment (default: 0, no filtering). Cannot be used with --skip-sort-index",
    )
    prepare_parser.add_argument(
        "--filter-threshold",
        type=min_max_float(0.0, 1.0),
        default=None,
        help="Minimum modification certainty to retain a site in the pileup. If not set, modkit will automatically determine a threshold. See github.com/nanoporetech/modkit/blob/master/filtering.md for more details.",
    )
    prepare_parser.add_argument(
        "--extract-reads",
        action="store_true",
        help="Whether to extract read-level features into a separate table.",
    )
    prepare_parser.add_argument(
        "--read-weights",
        type=pathtype.Path(exists=True, readable=True),
        default=None,
        help="read_scores.parquet from 'nanoflux score'. Builds the pileup from the extracted read calls with each read counted by its weight (restricted to the annotation sites) instead of running modkit pileup and bedtools; reads without a score get --unscored-weight",
    )
    prepare_parser.add_argument(
        "--unscored-weight",
        type=float,
        default=1.0,
        help="Weight of reads missing from --read-weights (default: 1.0)",
    )
    prepare_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Perform a dry-run without actually processing or writing files",
    )

    prepare_parser.set_defaults(func=prepare)

    infer_parser = subparsers.add_parser(
        "infer",
        help="Infer from a file generated by nanoflux prepare",
        formatter_class=parser.formatter_class,
        parents=[common_parser],
    )
    infer_parser.add_argument(
        "-i",
        "--input",
        type=pathtype.Path(exists=True, name_matches_re=r"\.bed$", readable=True),
        required=True,
        help="Path to input bed file",
    )

    infer_parser.set_defaults(func=infer)

    score_parser = subparsers.add_parser(
        "score",
        help="Score reads against a pooled CpG atlas and derive per-read weights",
        formatter_class=parser.formatter_class,
        parents=[common_parser],
    )
    score_parser.add_argument(
        "-i",
        "--input",
        type=pathtype.Path(exists=True, readable=True),
        required=True,
        help="Per-read call table: modkit extract read-calls TSV (from prepare --extract-reads) or a nanopolish/f5c call-methylation TSV, aligned to the atlas genome build",
    )
    score_parser.add_argument(
        "--format",
        choices=["modkit", "nanopolish"],
        default="modkit",
        help="Format of the input call table (default: modkit)",
    )
    score_parser.add_argument(
        "--atlas",
        type=pathtype.Path(exists=True, readable=True),
        required=True,
        help="Feather file with one row per CpG: chromosome, 1-based plus-strand C position, pooled methylated count, pooled total count",
    )
    score_parser.add_argument(
        "--atlas-columns",
        nargs=4,
        metavar=("CHROM", "POS", "METHYLATED", "TOTAL"),
        default=["chrom_x", "start_genomic", "methylated_pooled", "total_pooled"],
        help="Column names in the atlas (default: chrom_x start_genomic methylated_pooled total_pooled)",
    )
    score_parser.add_argument(
        "--min-atlas-cov",
        type=int,
        default=1,
        help="Ignore atlas sites with fewer pooled reads (default: 1)",
    )
    score_parser.add_argument(
        "--tau",
        type=float,
        default=1.0,
        help="Scale applied to log-likelihood ratios before the sigmoid (nanopolish format only)",
    )
    score_parser.add_argument(
        "--prior",
        nargs="+",
        default=["auto"],
        metavar="ALPHA_BETA",
        help="Beta prior for the atlas counts, p = (m + alpha) / (n + alpha + beta): 'auto' fits alpha and beta to the well-covered atlas sites (default), or pass two numbers, e.g. --prior 1 1",
    )
    score_parser.add_argument(
        "--prior-min-cov",
        type=int,
        default=100,
        help="Minimum pooled coverage of the atlas sites used to fit the automatic prior (default: 100)",
    )
    score_parser.add_argument(
        "--moments",
        type=str,
        default=None,
        help="Caller moments (what the caller reports at truly methylated / unmethylated CpGs): a moments.json from a previous run, or 'fit' to fit them on this sample. Default: the moments shipped with the package, fitted on CSF control samples",
    )
    score_parser.add_argument(
        "--moments-from",
        nargs="+",
        type=pathtype.Path(exists=True, readable=True),
        default=None,
        metavar="CALLS_TSV",
        help="Fit the caller moments on these read tables (pooled, e.g. the control samples) instead of using --moments; the result is written to moments.json and used for scoring",
    )
    score_parser.add_argument(
        "--moments-min-cov",
        type=int,
        default=50,
        help="Only atlas sites with at least this pooled coverage enter the moment fit, so that reads that are part of the atlas do not dominate the site probability (default: 50)",
    )
    score_parser.add_argument(
        "--weight-score",
        choices=["z", "llr_per_call"],
        default="z",
        help="Score the weight is built from: z (cross-entropy centred and scaled by what an atlas-like read would score, needs the caller moments) or llr_per_call (log-likelihood of the read under the atlas vs a flat model, per CpG; needs no moments). Default: z",
    )
    score_parser.add_argument(
        "--calibration",
        type=pathtype.Path(exists=True, readable=True),
        default=None,
        help="calibration.json: use a calibration table instead of the Beta prior. Must have been fitted on reads that are not part of the atlas",
    )
    score_parser.add_argument(
        "--fit-calibration",
        action="store_true",
        help="Fit a calibration table on this sample (which must not be part of the atlas) and score with it; writes calibration.json",
    )
    score_parser.add_argument(
        "--weight-mode",
        choices=["sigmoid", "hard"],
        default="sigmoid",
        help="sigmoid (default): w = sigmoid((center - z) / temperature), a smooth decreasing function of z with no data-derived cutoff; hard: 1 below the per-bin threshold from --weight-thresholds, --weight-min above",
    )
    score_parser.add_argument(
        "--weight-center",
        type=float,
        default=None,
        help="Score value at which the sigmoid weight is halfway between --weight-min and 1 (default: 0 for both scores, a read that fits the atlas)",
    )
    score_parser.add_argument(
        "--weight-temperature",
        type=float,
        default=None,
        help="Width of the sigmoid in score units; smaller sharpens the contrast between atlas-like and unlike reads (default: 1.0 for z, 0.25 for llr_per_call)",
    )
    score_parser.add_argument(
        "--weight-min",
        type=float,
        default=0.0,
        help="Weight floor so that atlas-like reads never vanish completely (default: 0.0)",
    )
    score_parser.add_argument(
        "--weight-thresholds",
        type=str,
        default=None,
        help="Per-bin z thresholds for --weight-mode hard, e.g. '1:-3,2:-3.8,3-4:-4.6,5-9:-5.8,10+:-8'",
    )
    score_parser.add_argument(
        "--chunksize",
        type=int,
        default=2_000_000,
        help="Rows of the call table processed at once (default: 2000000)",
    )
    score_parser.set_defaults(func=score)

    args = parser.parse_args(
        args=None if sys.argv[1:] else ["--help"]
    )  # display help if no subcommand is passed

    args.func(args)


if __name__ == "__main__":
    run()
